### ISSUE TITLE
latest update of @vue/cli broke this plugin

### ISSUE THREAD

**Issue by ntt2k** [andoshin11/vue-cli-plugin-nuxt-starter-template#1]
## package.json

```
"dependencies": {
    "nuxt": "^1.4.0",
    "vue": "^2.5.16"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.0.0-beta.15",
    "@vue/cli-plugin-eslint": "^3.0.0-beta.15",
    "@vue/cli-service": "^3.0.0-beta.15",
    "vue-cli-plugin-nuxt-starter-template": "^0.0.6",
    "vue-template-compiler": "^2.5.16"
  },
```

## yarn dev

```
 ERROR  Failed to compile with 1 errors                                                                                                         8:20:49 PM

 error  in ./.nuxt/client.js

Module build failed: Error: Plugin 0 specified in "/home/ntt2k/projects/try-nuxt/node_modules/@vue/babel-preset-app/index.js" provided an invalid property
 of "default" (While processing preset: "/home/ntt2k/projects/try-nuxt/node_modules/@vue/babel-preset-app/index.js")
    at Plugin.init (/home/ntt2k/projects/try-nuxt/node_modules/babel-core/lib/transformation/plugin.js:131:13)
    at Function.normalisePlugin (/home/ntt2k/projects/try-nuxt/node_modules/babel-core/lib/transformation/file/options/option-manager.js:152:12)
    at /home/ntt2k/projects/try-nuxt/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/home/ntt2k/projects/try-nuxt/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/home/ntt2k/projects/try-nuxt/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at /home/ntt2k/projects/try-nuxt/node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
    at /home/ntt2k/projects/try-nuxt/node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
    at Array.map (<anonymous>)
at OptionManager.resolvePresets (/home/ntt2k/projects/try-nuxt/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/home/ntt2k/projects/try-nuxt/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/home/ntt2k/projects/try-nuxt/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/home/ntt2k/projects/try-nuxt/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/ntt2k/projects/try-nuxt/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/ntt2k/projects/try-nuxt/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/home/ntt2k/projects/try-nuxt/node_modules/babel-core/lib/transformation/pipeline.js:46:16)

 @ multi webpack-hot-middleware/client?name=client&reload=true&timeout=30000&path=/__webpack_hmr ./.nuxt/client.js

 OPEN  http://localhost:3000 will be stuck forever
```

![screenshot from 2018-06-16 20-25-51](https://user-images.githubusercontent.com/4227421/41503847-9518f1e8-71a3-11e8-97e3-046edf428afd.png)

**Comment by pkej** [comment]
I made it work with nuxt-edge instead:

npm un nuxt -S
npm i nuxt-edge -S

**Comment by ntt2k** [comment]
thanks

**Comment by pbastowski** [comment]
@pkej I'm getting this same problem with the latest (13-Aug-2018) versions of nuxt-edge. The version from a few days still works, but all the new versions produce the above-mentioned error.  

Does anyone know what the actual problem was and how it was solved?

**Comment by Ayiga** [comment]
@pbastowski After playing around a bit, I determined the my issue was that I had installed either dependencies / devDependencies in my `package.json` file that conflicted with the `nuxt-edge` dependencies.  Specifically `babel-core` instead of the beta of `@babel/core`.  I just removed them from my package.json file and the issue seemed to of gone away.

Hope it helps,

~ Ayiga

**Comment by pbastowski** [comment]
@ayiga for me in the end it was also conflicting npm package versions. It’s working now. Thanks for answering my question.
